# Generated by Django 3.2.25 on 2025-07-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0052_cluster_zone_list"),
        ("db_meta", "0053_alter_tag_unique_together"),
    ]

    operations = []
